### ISSUE TITLE
put and getList not found?

### ISSUE THREAD

**Issue by amiral** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#10]
I not found that method? Can u help me.

tinydb.putList("MyUsers", mUsersArray);

**Comment by kcochibili** [comment]
Sorry for the confusion.  The method was renamed to 
`getListString()` https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L280

 and 

`putListString()`  https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L386

**Comment by amiral** [comment]
Okay. Thank kcochibili.  I got It. :)
