### ISSUE TITLE
putList,putListObject methods not found

### ISSUE THREAD

**Issue by Ni3Narale** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#15]
Hello putList,putListObject methods not found in the TinyDB class..

**Comment by kcochibili** [comment]
These are the putList methods:
https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L359
https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L400
https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L421
https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L442

Before you can use the putObject methods, you would must first download json.jar, then uncomment the lines starting at: Line31, Line317, Line332, Line462, Line468. 
(Look at the bottom of the ReadMe for full instruction on this)

**Comment by farmazon3000** [comment]
I think you can close it
