### ISSUE TITLE
Is this multi-process safe?

### ISSUE THREAD

**Issue by E3V3A** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#20]
Older APIs was using the broken MULTI_PROCESS_MODE. Then people noticed it was unsafe. 

Is this simplification reliable for multiple processes/services? 

How does this compare in performance to [tray](https://github.com/grandcentrix/tray) and [DPreference](https://github.com/DozenWang/DPreference), for example?

**Comment by kcochibili** [comment]
TinyDB does not have any special refinement for multiple processes, it is just a robust wrapper around the classic SharedPreference. 
Tray and DPreference focusses on multiProcesses, while TinyDB focusses on easy usage, and ability to save structured data like lists and objects.

**Comment by E3V3A** [comment]
Maybe add this to your FAQ. Closing.
