### ISSUE TITLE
Split Gson into plugable component

### ISSUE THREAD

**Issue by JFixby** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#23]
I see there is some hack to plug/unplug the Gson: ```Uncomment the save objects methods in your copy of TinyDB.java, starting at: Line31, Line317, Line332, Line462, Line468```

I may offer a solution where you can plug-in external components in a more elegant way. 

The idea is to wrap external component into interfaces and the ```TinyDB.class``` may call it's methods. On application start you can deploy the optional component if necessary.

Here is an example of how it can be done: https://github.com/Scarabei/Scarabei/blob/master/scarabei-api/src/com/jfixby/scarabei/api/desktop/DesktopSetup.java

Would you be interested?

**Comment by kcochibili** [comment]
Hello, sorry for my very late response. 
I would have liked the idea if this project was a full blown out library, but due to my focus simplicity for tinydb (copy and past the tinydb.java ). your sugestion won't align with the outcome. of having just one java file.
I appreciate your efforts

**Comment by JFixby** [comment]
No problem.

In case you need a full blown out library, here is an example of how to use it: 
https://github.com/Scarabei/Scarabei-examples/blob/master/scarabei-examples/src/com/jfixby/scarabei/examples/json/GsonExample.java

There is no documentation, so feel free to ask questions.
