### ISSUE TITLE
Question: Check if there is no List of String already?

### ISSUE THREAD

**Issue by kahloutme** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#27]
Hi,

I'm loving your library so firstly thank you very much. 

I am trying to check only grab an array list of strings from shared preferences only if they are null under a key. How can I do this?

**Comment by kcochibili** [comment]
TinyDB will return an empty list when you querry a non existent key. 
https://github.com/kcochibili/TinyDB--Android-Shared-Preferences-Turbo/blob/master/TinyDB.java#L283

and in most cases, Tinydb will also not allow you to save with a null value or null key
