### ISSUE TITLE
Wrong 2nd argument type

### ISSUE THREAD

**Issue by Tchoupinax** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#28]
Hello, 

i have a problem that i could not resolve. 
i have my custom class "Article" and want to put an Article ArrayList.
```Java
public class Article extends Object 
```

This problem explains all... :x 

```Java
ArrayList<Article> list = new ArrayList<Article>();
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
a.putObject("je", list.get(1)); // It works well
a.putListObject("tu", list); // It doesn't fuck*** work. Why ? :x
```
Your methods

```Java
public void putObject(String key, Object obj) // Object 
public void putListObject(String key, ArrayList<Object> objArray) // and Object... 
// Why it doesn't like Arraylist ? 
```

Thank you for your time.

**Comment by kcochibili** [comment]
TinyDB was designed with ArrayList in mind, and it was tested. 

what error are you getting when you try to put a list of objects?
 also, can you share the full ``Article`` class so I can see

**Comment by Tchoupinax** [comment]
Hello, 
That is my error : 
```Java
ArrayList<Article> list = new ArrayList<Article>();
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
list.add(new Article(1,"ok", "ok", "ok"));
a.putObject("je", list.get(1)); // It works well
a.putListObject("tu", list); // It doesn't fuck*** work. Why ? :x
```
![untitled](https://cloud.githubusercontent.com/assets/9136206/24292030/ccabca7e-108b-11e7-97d8-8b1de05189a2.png)

Article is a very simple class i created... i try to add "extends Object" but it happens nothing
```Java
**
 * Object ARTICLE
 */
public class Article extends Object {
    /**
     * Attributs
     */
    private int id;
    private String nom;
    private String categorie;
    private String imagePath;
    private Image image;
    private String magasin;

    /**
     * Constructeurs
     */
    public Article(int id, String nom, String categorie, String magasin) { 
    // code
    }

    public Article(int id, String nom, String categorie, String imagePath, Image image, String magasin) {
    //code
    }

    /**
     * Getters and Setters
     */
     // code

    /**
     * ToString method
     */
    @Override
    public String toString() {
    // code
    }
}
```

I agree what you did but i don't understand why it does not work with ArrayList<Article> **or other custom class i created** while it works with a single object of this class.

Thank you

**Comment by kcochibili** [comment]
Sorry I didn't specify in the instructions. 
But you have to individually cast the Articles to an Object before calling tinydb to save them.

here is an example:
```java
		ArrayList<Article> articles = new ArrayList<Article>();
		
		ArrayList<Object> articleObjects = new ArrayList<Object>();
		
		for(Article a : articles){
			articleObjects.add((Object)a);
		}
		
		tinydb.putListObject("todaysArticles", articleObjects);
```

then when you want to retrieve the Articles, convert the Objects gotten from tinydb back to Articles. 
```java
		ArrayList<Object> articleObjects = tinydb.getListObject("todaysArticles", Article.class);
		
		ArrayList<Article> articles = new ArrayList<Article>();
		
		for(Object objs : articleObjects){
			articles.add((Article)objs);
		}
```

**Comment by Tchoupinax** [comment]
Hello, 

Thank you for this answer. I thought about cast ArrayList<Article> to ArrayList<Object> but didn't think about cast each object... I learnt it ! :D 
I tried your tool and it works well... Very useful ! You did a great job.

Thank you for support.
Have a nice day.
