### ISSUE TITLE
putImage and getImage don't seem to work

### ISSUE THREAD

**Issue by Marcusjnr** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#32]
i used the putImage to save and image into TinyDB with the parameters but getting the image does not seem to work or am i doing something wrong
saving the image
` private void saveImage()
    {
        tinyDB.putImage("Splanner/profile","profilepic.png", photo);
    }`
getting the image
`Bitmap getImage = tinyDB.getImage("Splanner/profile");
        userDp.setImageBitmap(getImage);`

**Comment by kcochibili** [comment]
The ``putImage`` method returns the full address to the picture it saved. 
you have to save that path. and then use it to retrieve the image later.

here is an example: 
``String imageLocation = tinydb.putImage("Splanner/profile","profilepic.png", photo);``
``Bitmap myPic = tinydb.getImage(imageLocation);``

**Comment by Marcusjnr** [comment]
I want to get the image in another activity, how do i do that cause this code does not do that

**Comment by Marcusjnr** [comment]
Don't worry i have gotten it thanks very much
