### ISSUE TITLE
Replacing the image stored

### ISSUE THREAD

**Issue by Marcusjnr** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#33]
when i store an image and i want to replace it i do the same code for putting it in with the same path name so it replaces it but it gives me errors. (TinyDb.checkForNullValue).  Please is there another way to do it. That is to replace the image that has been stored in that path with another image

**Comment by kcochibili** [comment]
if you're getting a NullPointerException on the value, that means the you're passing in a value that is null. 
Let me see your full code.

**Comment by Marcusjnr** [comment]
alright here is my code i am calling the android default gallery taking the new picture and storing it in tinyDB or at least that is what i want to accomplish that is replace the image that is already stored there
`      Intent intent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
                    intent.setType("image/*");
                    intent.putExtra("crop", "true");
                    intent.putExtra("aspectX", 3);
                    intent.putExtra("aspectY", 4);
                    intent.putExtra("outputX",200);
                    intent.putExtra("outputY",200);
                    try {
                        intent.putExtra("return-data", true);
                        startActivityForResult(Intent.createChooser(intent,"Complete"), RESULT_LOAD_IMG);


                    } catch (ActivityNotFoundException e) {
                    }


                    String replaceImage = tinyDB.putImage("Splanner/profile","profilepic.png", photo);
                    tinyDB.putString("imagepath",replaceImage);


                    Bitmap getReplaceImage = tinyDB.getImage(tinyDB.getString("imagepath"));
                    circularImageView.setImageBitmap(getReplaceImage);`

**Comment by kcochibili** [comment]
This part of your code: should be in the ``OnActivityResult`` method of your activity.
Also, from the code you posted, I am still not seeing the source of the ``photo`` object you passed into  ``tinyDB.putImage("Splanner/profile","profilepic.png", photo);``



If your not good at getting images from the gallery, use this library to for image picking https://github.com/jkwiecien/EasyImage

**Comment by Marcusjnr** [comment]
The photo is handled in the onActivityResult
`    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        try {
            // When an Image is picked
            if (requestCode == RESULT_LOAD_IMG ) {
//            && resultCode == RESULT_OK
//                    && null != data

                Bundle extras2 = data.getExtras();
                if (extras2 != null) {
                    bitmap = extras2.getParcelable("data");
                    int width = bitmap.getWidth();
                    int height = bitmap.getHeight();


                    photo = Bitmap.createScaledBitmap(bitmap,width,height,true);
                    circularImageView.setImageBitmap(photo);

                }

            } else {
                Toast.makeText(getContext(), "You haven't picked Image",
                        Toast.LENGTH_LONG).show();
            }
        }
        catch (Exception e) {
            Toast.makeText(getContext(), "Something went wrong", Toast.LENGTH_LONG)
                    .show();
        }
    }`

**Comment by kcochibili** [comment]
TinyDB trows error when a value or a key is null. after analyzing your code, I am suspecting that the bitmap you are passing into tinydb here `` String replaceImage = tinyDB.putImage("Splanner/profile","profilepic.png", photo);`` the ``photo`` is null. 

I can tell because the error from  ``TinyDb.checkForNullValue`` happened here ''tinyDB.putString("imagepath",replaceImage);'' when you tried to save a null String object.

from your code, the only way it could be null is if  ``tinydb.putImage`` returned ``null``

So I would recommend you inspect the photo Bitmap and ensure it is not null before trying to save it into tinydb.

**Comment by Marcusjnr** [comment]
ya ya the error is from my code i have found it. Thanks for the help
