### ISSUE TITLE
If tinydb is null

### ISSUE THREAD

**Issue by hadiahmadi77** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#41]
hi thanks for your useful class . 
how can i find out if tinydb with key a is null or not . 
example : if (tinydb.getint("a") == null);

**Comment by kcochibili** [comment]
TinyDB does not store null values, to check if a value exists, you have to compare it to 0, if its a number, and the compare it to an empty String if its a String.

Example: 
`if (tinydb.getint("a") == 0 ){
 }`
`if (tinydb.getString("a").isEmpty() ){ 
}`

**Comment by hadiahmadi77** [comment]
Thanks

**Comment by hadiahmadi77** [comment]
i have one other question . 
im using class like this : 
    TinyDB tinyDB = new TinyDB(context);
        tinyDB.putInt("hadi" , 10);

but im getting this error : 
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

and  it say the error come from line 51 of tinyDB class

**Comment by hadiahmadi77** [comment]
i find it out . thanks for your help 👍
