### ISSUE TITLE
Not Really An Issue But More of A Question

### ISSUE THREAD

**Issue by Edge-Developer** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#44]
Can I use only one Instance of TinyDB to Store all of data? or do i have to create multiple to store multiple data

**Comment by kcochibili** [comment]
You can use multiple instances. It's okay. the data still stores in the same place and are synced.
This is because internally, Shared preferences uses a singleton instance. So whether you have one or multiple instances of TinyDB, it doesn't matter.

**Comment by Edge-Developer** [comment]
Thanks
