### ISSUE TITLE
Why not to make it as a singleton ?

### ISSUE THREAD

**Issue by AbdulelahAGR** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#49]
Hi there!
Why note making this class as a singleton or making it an option. I use it on my production app but I have modified it to be as a Singelton, so those who use shared preferences across their app, only initialize it once (when they use the TinyDB class for the first time). I can help to contribute to making these changes if the maintainer would approve.

**Comment by kcochibili** [comment]
Sorry I never attended to your question. I didn't make it a singleton for ease of use. A library like tinydb is used many times in an activity. I feel typing out TinyDB.getInstance(context) every single time would be unnecessary work, compared to a classically initialized object whose usage will now look like: tinydb.getString (no need to keep calling getInstance).

Also tinydb uses SharedPreferences internally which already is a singleton class
