### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by E3V3A** [kcochibili/TinyDB--Android-Shared-Preferences-Turbo#6]
Does this provide persistence to app closure and possible background kills? How does it perform in comparison to other storage methods? Perhaps you can say a few words in the README how to put this to use. We're looking for better and more efficient and simple methods for storing network/app information in [our app](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector), without SQLite overhead. Would this be suitable? Thanks.

**Comment by kcochibili** [comment]
Yes. It provides persistence to app closure. the data is stored on the phone system. not on temporary storage. The data is only deleted when the app is uninstalled.
Shared-Preferences is a fast easy way to store data using keys, the amount of data stored depends on the available storage on the phone. 

Depending on what you want to store, simply Initalize: ``TinyDB tinydb = new TinyDB(context);`` 
then call the method that corresponds to the object you want to store. (an example of this is in the ReadMe)

then when you want to get the stored data, simply say something like ``tinydb.getInt("Key");``

Yes I think this would be suitable for the kind of project you're working on. Its really just a robust wrapper of the default SharedPreferences In Android http://developer.android.com/training/basics/data-storage/shared-preferences.html

**Comment by E3V3A** [comment]
@kcochibili This sound really awesome, and I think we'll try to implement this. Especially since it seem that we could save arbitrary binary blobs by using the image support, as well. Two last questions: 
 1. Is this saved in memory or internal storage? (If it goes to storage, how often/when?)
 2. Do we need to add anything else to any XML file somewhere? 

Thank you so much for providing this and responding to my inquiry above.

**Comment by kcochibili** [comment]
SharedPreferences are stored in the Internal storage at ``/data/data/YOUR_PACKAGE_NAME/shared_prefs/YOUR_PACKAGE_NAME_preferences.xml``

No additional XML modification is needed. Just the ``TinyDB`` variable initialization.

**Comment by E3V3A** [comment]
Hi @kcochibili  So we've tried to implement your code [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/55fa0ceecfe577e6a19484a313a47ee5d45e0fe2) but it failed. (App compiles but crashes upon opening.) So I don't think we're doing the initialization correct... Perhaps you can lend us hand?

**Comment by kcochibili** [comment]
I did not see a  proper initialization in the code you linked.



this you have, is a wrong initialization approach.. 


```
public static Context context;
TinyDB tinydb = new TinyDB(context);
  private TinyDB(Context incomingContext){ 
         this.mContext = incomingContext;
         mContext = incomingContext; 
   }
  TinyDB.tinydb = new TinyDB(context);
```

TinyDB can be  or should be Initialized inside the RequestTask constructor like this:

```
   public TinyDB  tinydb;
    public RequestTask(Context context, char type) {
         mDbAdapter = new AIMSICDDbAdapter(mContext);
         tinydb = new TinyDB(context);                                                      
     }
```
the Context I used is  passed in from the constructor, which is the same as ``Activity.getApplicationContext();``

**Comment by E3V3A** [comment]
Thanks @kcochibili ! 
I didn't see your last post until just after having fixed my issue, in a slightly different, but seemingly equivalent way. I may implement your suggestion above, as it looks cleaner. Now it works, and it works faster and I love the new transparency it offers. Many cheers and compliments!
